apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-03-28T12:17:36Z"
  labels:
    kubernetes.io/metadata.name: kube-system
  name: kube-system
  resourceVersion: "9"
  uid: 61a0a54b-c885-49ba-ac6c-d4357079092b
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
